### ISSUE TITLE
Environment tablenos:no-prefix-table-caption undefined

### ISSUE THREAD

**Issue by obehrto** [tomduck/pandoc-xnos#13]
Hi,

when running pandoc  with --filter pandoc-xnos I get the following error:

! LaTeX Error: Environment tablenos:no-prefix-table-caption undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.654 \begin{tablenos:no-prefix-table-caption}

What is going on? 

Best,

Ole

**Comment by tomduck** [comment]
Sorry, but was this issue resolved?  Thanks, Tom
