### ISSUE TITLE
xnos-number-by-section=False is broken for (X)HTML

### ISSUE THREAD

**Issue by stroobandt** [tomduck/pandoc-xnos#15]
The `--metadata` customisation `xnos-number-by-section=False`

    -M xnos-number-by-section=False

is broken for (X)HTML. Numbering restarts with each section. This has been reported:

- for `fignos-number-by-section` [here](https://github.com/tomduck/pandoc-fignos/issues/76),
- for `tablenos-number-by-section` [here](https://github.com/tomduck/pandoc-tablenos/issues/17), and
- I have personally also experienced this bug for `eqnos-number-by-section`.

However, there is a pull request and a patch solving this issue waiting to be merged:

- for `tablenos-number-by-section` [here](https://github.com/tomduck/pandoc-tablenos/pull/18), and
- for `fignos-number-by-section` [here](https://github.com/tomduck/pandoc-fignos/issues/76#issuecomment-580267984).

There is also a very cumbersome [workaround](https://github.com/tomduck/pandoc-fignos/issues/76#issuecomment-613190630) that works for all `xnos` items when converting to (X)HTML.

Automatic numbering is an absolute **key feature** of the `pandoc-xnos` suite, but also a "deal-breaker" when not available. An expedient resolution of this bug is highly desirable.

**Comment by tomduck** [comment]
Thank you for this summary, which was helpful.  Sorry for the long wait.

The problems are now fixed in the `nextrelease` branch of each filter.    If problems persist beyond the next release, please feel welcome to re-open this Issue.

Tom

**Comment by stroobandt** [comment]
Many thanks, Tom. This now works flawlessly in `pandoc-xnos 2.4.3`.

**Comment by tomduck** [comment]
Wonderful.  Thanks for letting me know, Serge.  I appreciate the report and help with testing.  Cheers, Tom.
