### ISSUE TITLE
Is pandoc-xnos.exe a Haskell or Python exe?

### ISSUE THREAD

**Issue by w5m** [tomduck/pandoc-xnos#24]
I'm curious to know what/where the source of the pandoc-xnos.exe is? Is it a Python script packaged as an executable or is it compiled in some other language?

Many thanks.

**Comment by gepcel** [comment]
It's python.

**Comment by w5m** [comment]
Aha - I didn't realise Python scripts could be packaged as executables using tools like PyInstaller.
