### ISSUE TITLE
Feature: Remove redundant label

### ISSUE THREAD

**Issue by DaveJarvis** [tomduck/pandoc-xnos#3]
The label "Table:" is redundant:

``` .md
Table: Caption. {#tbl:id}
```

By reversing the table reference identifier, this could be:

``` .md
{#tbl:id} Caption.
```

This allows the author to change the label in a single location. Additionally, the same logic can be applied to equations, figures, and any other referenced element.

See also: https://github.com/jgm/pandoc/issues/813#issuecomment-298068508

**Comment by tomduck** [comment]
Thanks, @DaveJarvis.  I get what you are saying, but I think that this change would need to be made in pandoc itself.  Pandoc requires the table caption be formatted in a specific way.  For figures and equations the situation is even worse: pandoc processes the attributes before they are passed along to any filters.

At the moment I am using the syntax spec worked out in [jgm/pandoc#813](https://github.com/jgm/pandoc/issues/813) -- see [this post](https://github.com/jgm/pandoc/issues/813#issuecomment-70423503) by @scaramouche1.  It think that this will be pretty close to what pandoc ultimately adopts, although maybe better alternatives will emerge.

I am certainly happy to discuss more.

**Comment by tomduck** [comment]
I'm going to close this for now because it would require changes to pandoc.  If I am misreading this situation then please feel welcome to reopen the Issue.

**Comment by DaveJarvis** [comment]
Thanks, Tom. Hopefully the suggestion I made [a while back](https://github.com/jgm/pandoc/issues/813#issuecomment-298068508) can be integrated so that references can be made generic and the presentation logic around the caption type can be abstracted.
