### ISSUE TITLE
Cannot determine pandoc version.

### ISSUE THREAD

**Issue by hadrienj** [tomduck/pandoc-xnos#4]
I get this error message when I try to convert a md using pandoc and pandoc-fignos.

> Traceback (most recent call last):
>   File "/usr/local/bin/pandoc-fignos", line 7, in <module>
>     from pandoc_fignos import main
>   File "/usr/local/lib/python2.7/site-packages/pandoc_fignos.py", line 66, in <module>
>     PANDOCVERSION = pandocxnos.init(args.pandocversion)
>   File "/usr/local/lib/python2.7/site-packages/pandocxnos/core.py", line 186, in init
>     raise RuntimeError(textwrap.dedent(msg))
> RuntimeError: Cannot determine pandoc version.  Please file an issue at
>               https://github.com/tomduck/pandocfiltering/issues
> Error running filter pandoc-fignos:
> fd:12: hPutBuf: resource vanished (Broken pipe)

I saw [this issue](https://github.com/tomduck/pandoc-eqnos/issues/12) that seems related but was unable to use it to fix the problem.

Thanks!

**Comment by tomduck** [comment]
Thanks for your feedback, @hadrienj.  I just released the 1.0.0 versions of my filters today.  Can you please give them a try?  I don't think that this should be a problem any more.

**Comment by hadrienj** [comment]
Thank you for you answer!

I tried to upgrade pandoc-fignos with pip to the last version but pandoc doesn't find the pandoc-fignos executable now. I saw that the executable is in `/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/` but not in `/usr/local/bin/` (it is on osx). The command `which pandoc-fignos` doesn't give any output. Also, I wonder how to install the filters in a way that it is accessible from virtualenvs as well.

Thank you very much!

**Comment by tomduck** [comment]
Weird.  I have a couple of questions:

 1) Do you have multiple python installation or just the default version that came with your mac?
 2) Did you use sudo to install pandoc-fignos?

**Comment by hadrienj** [comment]
I should have multiple python installations. If I remember correctly I installed it with Homebrew. And I should have different binaries installed in my virtualenvs. I didn't use sudo to install pandoc-fignos.

**Comment by tomduck** [comment]
Can you give me the output of these bash commands?

    python --version
    pip --version

Unfortunately, I am not familiar with the use of virtualenvs.

**Comment by tomduck** [comment]
I should have asked for the following as well:

    which python
    which pip

**Comment by hadrienj** [comment]
/usr/local/bin/python

and

/usr/local/bin/pip

**Comment by tomduck** [comment]
OK, thanks.  That's definitely not the default python install, nor is it an install from python.org.

I would guess that the pandoc-fignos install location is not on your $PATH.  This is normally taken care of when python is installed, but maybe things are different for homebrew.

When I installed python from python.org, it put the following in my `.bash_profile`:

    # Setting PATH for Python 3.4
    PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
    export PATH

If you don't have a similar line in your `.bash_profile`, then you should put one in with the path to the pandoc-fignos install location.  You will need to restart your shell for it to take effect.  Be sure to test with `which pandoc-fignos`.

**Comment by hadrienj** [comment]
Great! Everything is working fine now!

Thank for the help and for the great work! That is very helpful!

**Comment by tomduck** [comment]
Fantastic!  I'm glad it all worked out.  Enjoy.
